# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b46eca983638669da96d3916571e50d0597a676f263aa0cbdd4b6847c00bf210965156de0273f0aec3fa9c20c8065d064ddf47a6c0441ec6896a2b582f442ba

test:
  secret_key_base: 5989154b3889f147391a50b145a0dc2d12f132d0e9c0049769626d8ea5508f49e5ff07500ec93aa655704aa84269b9541f5db368fcdfbe23a71dd097dde0c19d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
